# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_curveLandscape_wrappers", use_symbols = TRUE, package_name = "curveLandscape")

#' @usage NULL
#' @useDynLib curveLandscape, .registration = TRUE
NULL

#' Simulates birth, death and migration process of a multi-patch system.
#'
#'
sim_bdm <- function(n0, birth_baseline, death_baseline, t_max) .Call(wrap__sim_bdm, n0, birth_baseline, death_baseline, t_max)


# nolint end
