# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_curveLandscape_wrappers", use_symbols = TRUE, package_name = "curveLandscape")

#' @usage NULL
#' @useDynLib curveLandscape, .registration = TRUE
NULL

#' Returns the row and column from a 0-indexed, column-wise linear index `k` for a square matrix of dimension `n` x `n`
get_row_col <- function(k, n) .Call(wrap__get_row_col, k, n)

#' Returns the linear, 0-index id for (i,j) for n x n matrix.
get_linear_id <- function(i, j, n) .Call(wrap__get_linear_id, i, j, n)

#' Return the total number of elements in lower-triangular matrix (without diagonal)
get_total_number_of_elements <- function(n) .Call(wrap__get_total_number_of_elements, n)

get_habitat_island_ids <- function(neighbourhood) .Call(wrap__get_habitat_island_ids, neighbourhood)

WildSSA <- new.env(parent = emptyenv())

WildSSA$new_static <- function(n0, birth_baseline, death_baseline, carrying_capacity, migration_intercept, migration_baseline) .Call(wrap__WildSSA__new_static, n0, birth_baseline, death_baseline, carrying_capacity, migration_intercept, migration_baseline)

WildSSA$new_wedge <- function(n0, birth_baseline, death_baseline, carrying_capacity, migration_intercept, migration_baseline) .Call(wrap__WildSSA__new_wedge, n0, birth_baseline, death_baseline, carrying_capacity, migration_intercept, migration_baseline)

WildSSA$new_smooth <- function(n0, birth_baseline, death_baseline, carrying_capacity, migration_intercept, migration_baseline) .Call(wrap__WildSSA__new_smooth, n0, birth_baseline, death_baseline, carrying_capacity, migration_intercept, migration_baseline)

WildSSA$run_and_record_patch <- function(t_max, repetitions, seed) .Call(wrap__WildSSA__run_and_record_patch, self, t_max, repetitions, seed)

WildSSA$run_and_record_patch_par <- function(t_max, repetitions, seed) .Call(wrap__WildSSA__run_and_record_patch_par, self, t_max, repetitions, seed)

WildSSA$run_and_record_population <- function(t_max, repetitions, seed) .Call(wrap__WildSSA__run_and_record_population, self, t_max, repetitions, seed)

WildSSA$run_and_record_population_par <- function(t_max, repetitions, seed) .Call(wrap__WildSSA__run_and_record_population_par, self, t_max, repetitions, seed)

WildSSA$run_and_record_fixed_time_patches <- function(fixed_time_points, t_max, repetitions, seed) .Call(wrap__WildSSA__run_and_record_fixed_time_patches, self, fixed_time_points, t_max, repetitions, seed)

WildSSA$run_and_record_fixed_time_patches_par <- function(fixed_time_points, t_max, repetitions, seed) .Call(wrap__WildSSA__run_and_record_fixed_time_patches_par, self, fixed_time_points, t_max, repetitions, seed)

WildSSA$run_and_record_fixed_time_population <- function(fixed_time_points, t_max, repetitions, seed) .Call(wrap__WildSSA__run_and_record_fixed_time_population, self, fixed_time_points, t_max, repetitions, seed)

WildSSA$run_and_record_fixed_time_population_par <- function(fixed_time_points, t_max, repetitions, seed) .Call(wrap__WildSSA__run_and_record_fixed_time_population_par, self, fixed_time_points, t_max, repetitions, seed)

WildSSA$internal_debug_display <- function() .Call(wrap__WildSSA__internal_debug_display, self)

#' @export
`$.WildSSA` <- function (self, name) { func <- WildSSA[[name]]; environment(func) <- environment(); func }

#' @export
`[[.WildSSA` <- `$.WildSSA`

BirthDeathMix <- new.env(parent = emptyenv())

BirthDeathMix$new <- function(n0, birth_baseline, death_baseline, carrying_capacity, alpha_mix) .Call(wrap__BirthDeathMix__new, n0, birth_baseline, death_baseline, carrying_capacity, alpha_mix)

BirthDeathMix$run <- function(t_max, replicates, seed) .Call(wrap__BirthDeathMix__run, self, t_max, replicates, seed)

#' @export
`$.BirthDeathMix` <- function (self, name) { func <- BirthDeathMix[[name]]; environment(func) <- environment(); func }

#' @export
`[[.BirthDeathMix` <- `$.BirthDeathMix`


# nolint end
